layout_spectrum: 0.8491622
color:
  saturation: 0.9997709
  brandStrength: 0.6410928
  lightness: 0.896495
  brandColors:
    - '#0D0C0B'
    - '#886D43'
    - '#FBFBFF'
    - '#C6ACB3'
    - '#39536E'
  rhythmicContrast: 0.9478875
typography_spectrum: 0.6715525
name: Mestizo
